BlockSigner/cove

- site/config.yaml
- site/content/english/_index.md
- site/content/english/about.md
- site/content/english/imprint.md
- site/content/english/privacy.md
- site/content/german/_index.md
- site/content/german/about.md
- site/content/german/imprint.md
- site/content/german/privacy.md
- site/layouts/_default/single.html
- site/layouts/narrow/single.html
- site/layouts/partials/footer.html
- site/layouts/section/contact.html
- site/layouts/section/disclaimer.html
- src/css/main.scss
Add footer navigation and complete main navigation.
> feat(pages): prepare pages for corporate mini websites

- site/content/english/about.md
- site/content/english/terms-of-use.md
- site/content/german/about.md
- I filled in about in EN
- I changes some characters in terms-of-use EN
> About in EN, Terms-of-use EN

- site/content/english/about.md
- site/content/german/about.md
- src/css/imports/richtext.scss
Add max size to images in richtext and center them by default.
> feat(images): add picture element with jpg/webp images in markdown of about page

- site/content/english/terms-of-use.md
Some small adjustments from Eric.
> terms-of-use updates EN von Eric

- site/content/english/contact.md
- site/content/german/contact.md
Add proper spelling of Trust Square and format phone number consistently
with email signature and business cards.
> [MRG] content(contact): add space in 'Trust Square' and format phone

- site/content/english/_index.md
Some suggestions for changing up the language on the english main page.
It isn't perfect but feels more "english" to me than what we had before. Probably needs a few more iterations of word smithing to get it "just right".
> Tweak the language on the main page

- site/content/english/about.md
Related to #43 (same caveats apply)
> Tweak the language on the about page

- site/content/english/_index.md
- site/content/english/about.md
- site/content/english/contact.md
- site/content/english/imprint.md
- site/content/english/team.md
- site/content/german/_index.md
- site/content/german/about.md
- site/content/german/contact.md
- site/content/german/imprint.md
- site/content/german/team.md
Add for all but identification pages
> [MRG] feat(meta tags): add meta title and description

- site/config.yaml
- site/layouts/_default/baseof.html
> [MRG] fix(meta tags): link frontmatter of pages to metag tags in html head

- site/content/english/_index.md
- site/layouts/partials/intro.html
- src/css/imports/intro.scss
Also fixes issue with meta description on home
> [MRG] feat(intro): reduce width of intro

- site/config.yaml
- site/content/english/imprint.md
- site/content/english/team.md
- site/content/german/_index.md
- site/content/german/about.md
- site/content/german/imprint.md
- site/content/german/team.md
- src/css/imports/pricing.scss
- about
- imprint
- contact
- index
> Corrections

- site/content/english/_index.md
- site/content/english/contact.md
- site/content/english/team.md
> corrections-EN

- site/config.yaml
- site/layouts/partials/header.html
- src/css/imports/btn.scss
- src/css/imports/contact.scss
- src/css/imports/footer.scss
- src/css/imports/header.scss
- src/css/imports/id-block.scss
- src/css/imports/lan-nav.scss
- src/css/imports/outro.scss
- src/css/imports/price-plan.scss
- src/css/imports/pricing.scss
Fix issues with horizontal scrolling on home page for mobile viewports.
> feat(try it out): add button to header

- site/config.yaml
- site/content/english/_index.md
- site/content/english/imprint.md
- site/content/english/privacy.md
- site/content/german/identification.md
- site/content/german/imprint.md
- site/content/german/privacy.md
- site/layouts/partials/id-block.html
- links target _blank
- some text corrections in german
- identification links target _blank
> Multiple corrections

- src/css/imports/hs-cookie-consent.scss
- src/css/main.scss
This is an attempt to style the dynamically loaded hubspot cookie consent banner.
> [MRG] feat(cookies): add hubspot cookie consent styling

- src/css/imports/hs-cookie-consent.scss
This is an attempt to style the dynamically loaded hubspot cookie consent banner.
> feat(cookies): add hub spot cookie consent styling

- site/content/english/identification.md
> [MRG] Update the english identification page

- site/content/german/identification.md
Die Details zur Identitätsprüfung für das Signieren mit Skribble findest du in unserem Factsheet.
> correction Identifkation DE

- site/layouts/_default/baseof.html
- site/layouts/partials/footer.html
- site/layouts/partials/language-switch-js.html
If the user visits the page on a different language than their preset
browser language, cove will now redirect them to their language.
Currently there is only german supported.
> [MRG] feat(browser language): implement redirection to browser language

- site/config.yaml
- site/layouts/partials/footer.html
- site/layouts/partials/newsletter.html
- src/css/imports/footer.scss
- src/css/imports/lan-nav.scss
- src/css/imports/newsletter.scss
- src/css/main.scss
Introduces new menus in the footer. Team was moved in to the footer.
> [MRG] feat(footer): add new footer that includes newsletter component

- site/layouts/_default/baseof.html
- src/css/main.scss
Adding the @font-face rule-set in the base html. Change font-display to auto
> [MRG] feat(fonts): optimizing font loading

- site/config.yaml
- site/layouts/partials/footer.html
- src/css/imports/footer.scss
Adds a link to the knowledge base (help.srkibble.com). Also, optimizes whitespace use inside of the footer for improved legibility.
> [MRG] feat(footer): Add 3rd navigation column with ressource links

- site/layouts/partials/mobile-nav.html
- src/css/imports/mobile-nav.scss
Login was not accessible on mobile devices. The login link is placed inside of the mobile navigation.
> [MRG] feat(login): add login link to mobile viewport

- site/content/english/_index.md
- site/content/english/about.md
- site/content/english/contact.md
- site/content/english/identification.md
- site/content/english/team.md
- site/content/french/_index.md
- site/content/german/_index.md
- site/content/german/about.md
- site/content/german/contact.md
- site/content/german/identification.md
- site/content/german/team.md
- site/layouts/partials/header.html
Because my.skribble.com is currently down.
> [MRG] fix(platform links): remove all links to my.skribble.com

- site/content/english/_index.md
- site/content/english/about.md
- site/content/english/contact.md
- site/content/english/identification.md
- site/content/english/team.md
- site/content/french/_index.md
- site/content/german/_index.md
- site/content/german/about.md
- site/content/german/contact.md
- site/content/german/identification.md
- site/content/german/team.md
- site/layouts/partials/header.html
> Revert "[MRG] fix(platform links): remove all links to my.skribble.com"

- src/css/imports/collapsible.scss
- src/css/imports/id-block.scss
- src/css/imports/id-steps.scss
- src/css/imports/person.scss
- src/css/imports/plan.scss
- src/css/main.scss
Mainly concerns fixing flex layout where content is drawn on top of each other
> [MRG] feat(ie11): add support for ie11 (sigh)

- site/config.yaml
- site/content/english/identification.md
- site/content/english/sav-fsa.md
- site/content/french/sav-fsa.md
- site/content/german/identification.md
- site/content/german/sav-fsa.md
Changes in:
- config.yaml - EN, DE, FR
- identification.md - EN, DE
- SAV-FSA.md - EN, DE, FR
> Appointment links

- site/config.yaml
- site/content/french/imprint.md
- site/content/french/sav-fsa.md
- I changed the text "Impressum" for FR.
- 1 type utilisent
- tu = > vous
> [MRG] text-corrections

- site/content/english/terms-of-use.md
- site/content/french/terms-of-use.md
- site/content/german/terms-of-use.md
- terms-of-use FR
- correction title terms-of-use DE
- correction title terms-of-use EN
- correction title terms-of-use FR
> fr-terms-of-use

- site/config.yaml
- little typo in DE - Datenschutzerklärungen.
> text-correction

- site/content/german/_index.md
- site/content/german/about.md
- site/content/german/identification.md
- site/content/german/media.md
Little typo corrections from Luc.
> [MRG]de-text-corrections

- site/content/french/identification.md
> [MRG]factsheet-fr-replacement

- site/content/german/services.md
- the offre tilte in DE had a wrong language in the headline
> [MRG]offre-title

- site/content/english/identification.md
- text correction of the 4 steps
> [MRG]id-correction-4steps

- site/content/german/services.md
- set a point at the end of the lead
> [MRG] correction-lead

- site/content/english/_index.md
- site/content/english/about.md
- site/content/english/contact.md
- site/content/english/identification.md
- site/content/english/media.md
- site/content/english/sav-fsa.md
- site/content/english/services.md
- site/content/french/_index.md
- site/content/french/about.md
- site/content/french/contact.md
- site/content/french/identification.md
- site/content/french/media.md
- site/content/french/sav-fsa.md
- site/content/french/services.md
- site/content/german/_index.md
- site/content/german/about.md
- site/content/german/contact.md
- site/content/german/identification.md
- site/content/german/media.md
- site/content/german/sav-fsa.md
- site/content/german/services.md
> [MRG] content: add alt text for images

- site/content/english/_index.md
- site/layouts/shortcodes/picture.html
Follow up to #137 where we added the text but it doesn't show up on the site afterwards.
> [MRG] Update picture shortcode to use positional argument for alt attribute

- site/content/english/imprint.md
- site/content/english/privacy.md
- site/content/english/terms-of-use.md
- site/content/french/imprint.md
- site/content/french/privacy.md
- site/content/french/terms-of-use.md
- site/content/german/imprint.md
- site/content/german/privacy.md
- site/content/german/terms-of-use.md
Change from BlockSigner AG to Skribble AG
- terms-of-use in EN, DE, FR
- privacy-policy in EN, DE, FR
- imprint in EN, DE, FR
> [MRG]Skribble-AG-Change

- site/static/my.skribble/status.txt
In order to test the display of such messages in the new UI of Skribble.
> [MRG] Update status.txt with a temporary text

- site/content/german/_index.md
Diesen Alt text habe ich auf DE noch vergessen
> Update(index): add SEO Alt Text for pics

- site/layouts/_default/baseof.html
This is the container Tag of matomo.
> Update(baseof): Add matomo Tracking js (Container Tag)

- site/static/my.skribble/status.txt
> Revert "Update status.txt for testing"

- site/content/english/contact.md
- site/content/french/contact.md
- site/content/german/contact.md
> [MRG] BlockSigner is out, Skribble is in!

- site/content/english/explainer-qes.md
Adds a missing quote, spotted by Simon 🕵️‍♂️
> [MRG] Fix missing quote

- site/content/french/explainer-qes.md
- site/content/german/explainer-qes.md
Content was not translated. Oops.
Closes https://app.asana.com/0/995964219886332/1136900979376562/f
> [MRG] fix(QES explained): Translate outro component

- site/content/english/_index.md
- site/content/french/_index.md
- site/content/german/_index.md
On english and german home there were some content issues.
Closes https://app.asana.com/0/1136100794049714/1123176981544282
> [MRG] content(home): fix some content issues

- package.json
- site/content/english/terms-of-use.md
- site/content/french/terms-of-use.md
- site/content/german/terms-of-use.md
- site/layouts/shortcodes/legal-list.html
- src/css/imports/legal-list.scss
- src/css/imports/mixins.scss
- src/css/main.scss
- yarn.lock
To allow for unique legal references in our legal documents.
Improve content by using markdown instead of html.
See https://github.com/BlockSigner/wave/pull/459
> [MRG] feat(ToU): Add shortcode legal-list to style lists with incrementing numbers

- site/static/my.skribble/status.txt
Change error message to only mention Mobile ID.
> [MRG] SC is back again

- site/content/german/explainer-qes.md
> [MRG]Update explainer: typo

- site/content/english/explainer-qes.md
- site/content/english/hr.md
- site/content/english/lawyer.md
- site/content/french/explainer-qes.md
- site/content/french/hr.md
- site/content/french/lawyer.md
- site/content/german/explainer-qes.md
- site/content/german/hr.md
- site/content/german/lawyer.md
Added meta tags (title and descriptions) and alt texts on the new pages:
- hr
- lawyer
- explainer-qes
> SEO Update: Meta tags & alt texts

- site/content/english/agb.md
- site/content/french/agb.md
- site/content/german/agb.md
Was still August. Which is wrong. Ofc.
> [MRG] feat(GTC): Update date of the GTC

- site/static/my.skribble/status.txt
> Revert "[MRG] Vault unreachable status message"

- site/content/german/signaturestandards.md
> [MRG] Fix typo

- site/content/german/lawyer.md
Some typo fixes are now verfuegnar.
> [MRG] fix(lawyer): fix typos in the german lawyer page

- site/config.yaml
- site/content/english/privacy.md
- site/content/french/privacy.md
- site/content/german/privacy.md
Fix links of mobile nav footer links in english and add in other
languages. Insert soft hyphen in title of Datenschutzbestimmungen page.
Closes https://app.asana.com/0/995964219886332/1144647320352234
> [MRG] fix(mobile nav): add mobile nav footer links

- README.md
- site/config.yaml
- site/content/english/_index.md
- site/content/english/contact.md
- site/content/english/enable-qes.md
- site/content/english/hr.md
- site/content/english/identification.md
- site/content/english/lawyer.md
- site/content/english/signaturestandards.md
- site/content/french/_index.md
- site/content/french/enable-qes.md
- site/content/french/hr.md
- site/content/french/identification.md
- site/content/french/lawyer.md
- site/content/french/qes-validator.md
- site/content/french/signaturestandards.md
- site/content/german/_index.md
- site/content/german/enable-qes.md
- site/content/german/features.md
- site/content/german/hr.md
- site/content/german/identification.md
- site/content/german/lawyer.md
- site/content/german/signaturestandards.md
Korrekturen vor dem GO-Live für Website
> Lots of small text changes and polishing

- site/content/english/_index.md
- site/content/french/_index.md
- site/content/german/_index.md
Changed order of last teaser in three steps
to sign legally - only in english
Changed btn to outline in what is a QES?
Add title sign in three steps for de, fr, en
> [MRG] Home - some corrections

- site/static/my.skribble/status.txt
> Revert "Update status.txt"

- site/content/english/enable-qes.md
- site/content/french/enable-qes.md
- site/content/german/enable-qes.md
> [MRG] FAQ-Changes

- site/config.yaml
- site/layouts/partials/header.html
- src/css/imports/header.scss
Solves first 2 subtasks of https://app.asana.com/0/1127348355003379/1144623825294181/f
> [MRG]: feat(Navigation Bar): Visual Improvements

- site/content/english/features.md
- site/content/english/integration.md
- site/content/english/qes-validator.md
- site/content/english/signaturestandards.md
- site/content/french/enable-qes.md
- site/content/french/features.md
- site/content/french/integration.md
- site/content/french/qes-validator.md
- site/content/french/signaturestandards.md
- site/content/german/features.md
- site/content/german/integration.md
- site/content/german/qes-validator.md
- site/content/german/signaturestandards.md
Meta data and alt texts changed and added
> [MRG] Meta data and alt texts changed and added

- site/content/english/_index.md
The document to upload does not have to be signed.
> [MRG] Fix wrongly translated text in english

- site/content/english/expert-suisse.md
- site/content/french/expert-suisse.md
- site/content/german/expert-suisse.md
> [MRG] Update expertsuisse: text

- README.md
Adds to README:
- Table of contents
- New components
- cta (new parameters)
- cta-group
- action-card
- heading (new parameters)
> [MRG] docs(Table of contents + new components): Adds new content to README

- site/content/english/_index.md
- site/content/english/features.md
- site/content/french/features.md
- site/content/german/features.md
- site/static/features/visual-signature.svg
First I adjusted a typo:
Changed Button "Show all function" on EN to "Show all features"
> [MRG] Add feature: visual signature composer

- site/content/english/enable-qes.md
- site/content/english/team.md
- site/content/french/enable-qes.md
- site/content/french/team.md
- site/content/german/enable-qes.md
- site/content/german/team.md
- Deleted lead-text in title Advisors from Teams-site
> [MRG] Changes: Leadtext Team and RA-FlexOffice

- src/css/imports/hs-cookie-consent.scss
Solves https://app.asana.com/0/995964219886332/1147478985512681/f
Unfortunately can only be 100% tested once it reaches production, as the cookie bar is only displayed in production. But shouldn't affect anything else, so it's low risk
> [MRG] feat(Cookie Banner CSS): Improves cookie banner CSS

- src/css/imports/hs-cookie-consent.scss
Should be deployed and tested on production
> [MRG] Improve cookie banner

- site/static/my.skribble/status.txt
> [MRG] Revert "Update status.txt"

- site/content/english/team.md
- site/content/french/team.md
- site/content/german/team.md
- site/layouts/partials/person.html
- site/layouts/team/single.html
- src/css/imports/mixins.scss
- src/css/imports/person.scss
While ensuring the color sequence: permutations of yellow, red, purple.
@dkumpf1, we reduced the whitespace between images, use all landscape format, and changed the breakpoint for smaller viewports. Pictures change layout with wider viewports now. The text distance to the image has been increase for smaller viewports. It's a general optimization for a better overview. Skribblers are now placed randomly while keeping the color sequence. Anybody can be in the 1st place now 🤩
Could you check if the layout looks correct on all devices/browsers?
> [MRG] feat(Team): Randomly sort team members

- site/content/english/enable-qes.md
- site/content/french/enable-qes.md
- site/content/german/enable-qes.md
Was temporarily removed from the list in https://github.com/BlockSigner/cove/pull/238
> [MRG] feat(Location): Re-add flexoffice as Skribble ident location

- site/config.yaml
- site/layouts/partials/footer-language-switcher.html
- Changed position of copyright
- Add GTC-Link in footer for EN, DE, FR
> [MRG] Add GTC in Footer

- site/content/english/contact.md
- site/content/french/contact.md
- site/content/german/contact.md
Add new address FlexOffice and changed
the text by the headline
> [MRG] FlexOffice office address

- site/content/english/imprint.md
- site/content/french/imprint.md
- site/content/german/imprint.md
Changed address in imprint for EN, DE, FR
> [MRG] new address in imprint

- site/config.yaml
- site/content/english/gtc.md
- site/content/english/privacy.md
- site/content/english/terms-of-use.md
- site/content/french/gtc.md
- site/content/french/privacy.md
- site/content/french/terms-of-use.md
- site/content/german/gtc.md
- site/content/german/privacy.md
- site/content/german/terms-of-use.md
- site/layouts/partials/footer-language-switcher.html
Add terms-of-use to the footer
Deleted year 2019 on @ Skribble
Changed some texts on terms-of-use to contact us in
DE, EN, FR
> [MRG] Footer: ToU

- site/content/german/careers/sales-manager-de.md
> [MRG] Fix missing fullstop

- site/content/english/careers/sales-manager-de.md
- site/content/french/careers/sales-manager-de.md
- site/content/german/careers/sales-manager-de.md
Corrected the wrong displayed bulletpoints in the code
> [MRG] jobspage - wrong displayed bulletpoints

- site/content/english/features-business.md
> [MRG] Language tweaks

- site/layouts/_default/baseof.html
> [MRG] Update(baseof.html): Add new matomo tag manager

- site/content/english/_index.md
- site/content/english/features-business.md
- site/content/english/hr.md
- site/content/english/integration.md
- site/content/english/lawyer.md
- site/content/english/signaturestandards.md
- site/content/french/_index.md
- site/content/french/careers.md
- site/content/french/enable-qes.md
- site/content/french/features-business.md
- site/content/french/hr.md
- site/content/french/integration.md
- site/content/french/lawyer.md
- site/content/french/signaturestandards.md
- site/content/german/_index.md
- site/content/german/integration.md
- site/content/german/lawyer.md
- site/content/german/signaturestandards.md
- src/css/imports/logos-container.scss
- Changed wrong place Fribourg testimonial
- Corrected some paragraph wrap on index and integration
> [MRG] Integrated hidden legal weight, paragraph wrap changes, placed testimonial to correct possition

- site/config.yaml
- site/content/english/identification.md
> [MRG] feat(Navigation): Add links to root elements of navi

- site/content/english/signaturestandards.md
Our signatures aren't all signing and dancing, yet!
> fix(typo): siNgature -> signature

- site/config.yaml
- site/content/english/enable-qes.md
- site/content/english/features.md
- site/content/english/hr.md
- site/content/english/integration.md
- site/content/english/lawyer.md
- site/content/french/integration.md
- site/content/german/_index.md
- site/content/german/enable-qes.md
- site/content/german/expert-suisse.md
- site/content/german/features-business.md
- site/content/german/features.md
- site/content/german/hr.md
- site/content/german/integration.md
- site/content/german/lawyer.md
- site/content/german/sav-fsa.md
This PR fixes several typos in our website.
> [MRG] Fixing typos

- site/content/french/expert-suisse.md
Any means of contact are currently missing at the bottom of the page. This PR re-introduces the
expected content.
> [MRG] fix(Expert suisse): Show contact details at the bottom of the page

- site/content/french/expert-suisse.md
> [MRG] fix(expertsuisse): richtext tag for intro block

- site/content/english/signaturestandards.md
closes https://app.asana.com/0/995964219886332/1164631387046537/f
> [MRG] Use AES instead of FES in English

- site/content/english/enable-qes.md
- site/content/french/enable-qes.md
- site/content/german/enable-qes.md
Changed the address and google-maps link for crativ
> [MRG] Changed the address and google-maps link

- site/content/german/lawyer.md
Add ID-Reference for url anker to jump to Use-Case Headline
> [MRG] Altenburger anker id

- site/content/english/partners.md
- site/content/french/partners.md
- site/content/german/partners.md
Spectas had as a title "Hosting" which is not right. Changed it to
"Software & Integration".
> [MRG] update(partners): set better spectas title

- site/content/english/identification/aes-for-business/index.md
There was a N missing from evaluation. 
I think we mean certificate provider, not certification provider.
> [MRG] AES4biz page language tweaks

- site/content/french/identification/aes-for-business/index.md
> [MRG] fix(French): Add missing translation

- site/content/english/identification/aes-for-business/index.md
first.last @ example.com (with white spaces) looked too weird so proposing to remove them. Switched to jsmith@yourdomain.com to make it gender neutral.
> [MRG] Remove whitespace from email address

- site/content/english/identification/aes-for-business/index.md
- site/content/french/identification/aes-for-business/index.md
- site/content/german/identifikation/aes-for-business/index.md
Closes https://app.asana.com/0/1117355270601225/1168025902221425
> [MRG] fix(A4B): add proper meta-title and meta-description contents

- site/content/english/identification.md
- site/content/french/identification.md
- site/content/german/identification.md
Added cooming soon on identification on e-id section. Because various interested clients
are calling and believe it is already possible
> [MRG] E-ID's coming-soon 

- site/content/english/signaturestandards.md
- Added the tip from David to wrap h1 title in EN
> [MRG] Wrap adapted by e-signature EN

- site/content/german/signaturestandards.md
Added the tip from David to wrap h1 title in DE
> [MRG] Wrap adapted by e-signature for DE

- site/content/french/signaturestandards.md
- Added the tip from David to wrap h1 titles in FR
> [MRG] Wrap adapted by e-signature FR

- site/content/english/careers.md
- site/content/english/careers/country-manager-de.md
- site/content/english/careers/customer-success-manager-de.md
- site/content/english/careers/sales-manager-de.md
- site/content/french/careers.md
- site/content/french/careers/country-manager-de.md
- site/content/french/careers/customer-success-manager-de.md
- site/content/french/careers/sales-manager-de.md
- site/content/german/careers.md
- site/content/german/careers/country-manager-de.md
- site/content/german/careers/customer-success-manager-de.md
- site/content/german/careers/sales-manager-de.md
- Changed job-page for sales manager de
- Added job-page for country manager de
- Added job-page for customer success manager de
> [MRG] new jobs on career

- site/content/english/identification.md
- site/content/english/identification/aes-for-business/index.md
- site/content/english/signaturestandards.md
- site/content/french/identification.md
- site/content/french/identification/aes-for-business/index.md
- site/content/french/signaturestandards.md
- site/content/german/identification.md
- site/content/german/identifikation/aes-for-business/index.md
- site/content/german/price.md
- site/content/german/signaturestandards.md
- Added teaser to the full legal-weight barometer pdf in DE, EN, FR
- Only DE link is correct
- Waiting for EN and FR translation to add correct link on EN and FR teaser
> [MRG] Barometer adjustments

- site/config.yaml
Added status-page in footer on the DE and FR page
> [MRG] Status-page in footer for DE and FR

- site/content/english/careers.md
- site/content/english/careers/account-executive-ch.md
- site/content/french/careers.md
- site/content/french/careers/account-executive-ch.md
- site/content/german/careers.md
- site/content/german/careers/account-executive-ch.md
Added new job for account executive CH in DE, EN, FR
> [MRG] Job Account Executive for CH

- README.md
- site/config.yaml
- site/content/english/price.md
- site/content/french/price.md
- site/content/german/price.md
- site/layouts/partials/header.html
- site/layouts/shortcodes/action-card.html
- src/css/imports/action-card.scss
**Changed on pricing DE:**
- Content for Free
- Content for Business
**Changed on Config.yaml in DE footer:**
- Beweikraft bestimmen
- Kontakt aufnehmen
> [MRG] Pricing MVP0

- site/config.yaml
- site/content/english/contact.md
- site/content/french/contact.md
- site/content/german/contact.md
- site/layouts/contact/single.html
Changed the text for the 2 CTA in Footer.
Only for EN and FR.
> [MRG] Footer update and contact

- site/content/english/features-business.md
- site/content/french/features-business.md
- site/content/german/features-business.md
Removed first feature on business-features because is no longer up-to-date with the current pricing.
> [MRG] Business-features update

- README.md
A first run showed that we made some mistakes. So next time, there's help in the readme.
> [MRG] docs(status.txt): Add instructions on how to change status in WAVE

- README.md
> [MRG] docs(toc): Add toc for newly introduced section

- site/config.yaml
Changed only CTA-text in footer for increase legal weight for EN DE FR
> [MRG] CTA increase legal weight

- site/content/english/enable-qes.md
- site/content/english/identification.md
- site/content/french/enable-qes.md
- site/content/french/identification.md
- site/content/german/enable-qes.md
- site/content/german/identification.md
- Changed link in identification on online-id to the enable-qes page
- Removed Corona teaser on enable-qes
- Added new FlexOffice RA-ID phone number and time
> [MRG] update: CTA identification and enable-qes

- site/content/english/enable-qes.md
- site/content/english/price.md
- site/content/english/team.md
- site/content/french/enable-qes.md
- site/content/french/price.md
- site/content/french/team.md
- site/content/german/enable-qes.md
- site/content/german/price.md
- site/content/german/team.md
Changed on team page function of Soraya.
> [MRG] Text corrections

- site/content/english/_index.md
- site/content/french/_index.md
- site/content/german/_index.md
It was supposed to be a no-name-statement
> [MRG] Correction swiscanto statement 

- site/content/english/careers.md
- site/content/english/careers/account-executive.md
- site/content/english/careers/sales-consultant.md
- site/content/english/careers/sales-development-representative.md
- site/content/english/careers/success-manager.md
- site/content/french/careers.md
- site/content/french/careers/account-executive.md
- site/content/french/careers/sales-consultant.md
- site/content/french/careers/sales-development-representative.md
- site/content/french/careers/success-manager.md
- site/content/german/careers.md
- site/content/german/careers/account-executive.md
- site/content/german/careers/sales-consultant.md
- site/content/german/careers/sales-development-representative.md
- site/content/german/careers/success-manager.md
> [MRG] update careers - sales

- site/content/english/careers/account-executive.md
- site/content/english/careers/sales-consultant.md
- site/content/english/careers/sales-development-representative.md
- site/content/english/careers/success-manager.md
- site/content/french/careers/account-executive.md
- site/content/french/careers/sales-consultant.md
- site/content/french/careers/sales-development-representative.md
- site/content/french/careers/success-manager.md
- site/content/german/careers/account-executive.md
- site/content/german/careers/sales-consultant.md
- site/content/german/careers/sales-development-representative.md
- site/content/german/careers/success-manager.md
Added og image path to 4 sales jobs in EN
> [MRG] Sales jobs - og images

- site/config.yaml
- site/content/english/increase-legal-weight.md
- site/content/english/team.md
- site/content/french/increase-legal-weight.md
- site/content/french/team.md
- site/content/german/increase-legal-weight.md
- site/content/german/team.md
I made three minor adjustments: 
- Maxim's job title changed to Chief Growth Officer
- Sub-Nav Platform: AES for BIZ and Enable-QES removed, as it is now solved by increasing legal weight
- Increase legal weight: removed "cta-group" tag so that the phone call teaser stands alone.
> [MRG] Sub-nav and job-function

- site/content/english/identification.md
- site/content/french/identification.md
- site/content/german/identification.md
> [MRG] Removed Identity Easy

- site/content/english/careers/success-manager.md
- site/content/french/careers/success-manager.md
- site/content/german/careers/success-manager.md
Changed link to survey for success manager in DE, EN, FR
> [MRG] Changed link to survey for success manager

- site/content/english/identification/aes-for-business/index.md
- site/content/french/identification/aes-for-business/index.md
- site/content/german/identifikation/aes-for-business/index.md
von 5-6 Tagen zu 1-2 Wochen da unrealistisch
> [MRG] Update Korrektur bei Dauer FES for Business

- site/content/english/price.md
- site/content/french/price.md
- site/content/german/price.md
As discussed with Eric and Simon.
> [MRG] Adapt billing description for Business Model

- site/content/english/enable-qes.md
- site/content/french/enable-qes.md
- site/content/german/enable-qes.md
Changes phone number and office name by Patrick's request
> [MRG] feat(Update Flexoffice Details): Changes phone number and office name

- site/layouts/status/single.html
Show each maintenance entry defined here: https://status.skribble.info/dashboard/schedule 
as long as the "schedulet at" date time lies within the last 5 days days and the "completed at" datetime of this maintenance is not expired yet.
https://app.asana.com/0/1185226250963162/1183504138569684
> [MRG] Statuspage update maintenance section

- site/config.yaml
- site/content/english/gtc-archive.md
- site/content/english/gtc-v2019-10-01.md
- site/content/english/privacy-v2018-10-18.md
- site/content/english/privacy-v2019-10-22.md
- site/content/english/terms-of-use-archive.md
- site/content/english/terms-of-use-v2018-10-18.md
- site/content/english/terms-of-use-v2019-10-01.md
- site/content/french/gtc-archive.md
- site/content/french/gtc-v2019-10-01.md
- site/content/french/privacy-archive.md
- site/content/french/privacy-v2018-10-18.md
- site/content/french/privacy-v2019-10-22.md
- site/content/french/terms-of-use-archive.md
- site/content/french/terms-of-use-v2018-10-18.md
- site/content/french/terms-of-use-v2019-10-01.md
- site/content/german/gtc-archive.md
- site/content/german/gtc-v2019-10-01.md
- site/content/german/privacy-archive.md
- site/content/german/privacy-v2018-10-18.md
- site/content/german/privacy-v2019-10-22.md
- site/content/german/terms-of-use-archive.md
- site/content/german/terms-of-use-v2018-10-18.md
- site/content/german/terms-of-use-v2019-10-01.md
This will bring the archive structure of our Privacy Policy to our GTC
and Terms of Use. It will fix some inconsistencies as well.
Closes https://app.asana.com/0/1187035237749018/1186660118928177
> feat(archives): replicate archive structure for GTC and ToU

- site/content/english/_index.md
- site/content/english/careers.md
- site/content/english/careers/account-executive.md
- site/content/english/careers/sales-development-representative.md
- site/content/english/careers/senior-success-manager.md
- site/content/english/careers/success-manager.md
- site/content/french/careers.md
- site/content/french/careers/account-executive.md
- site/content/french/careers/sales-development-representative.md
- site/content/french/careers/senior-success-manager.md
- site/content/german/careers.md
- site/content/german/careers/account-executive.md
- site/content/german/careers/sales-development-representative.md
- site/content/german/careers/senior-success-manager.md
- site/content/german/careers/success-manager.md
- Add new Job-Profile EN for Senior Success Manager
- Add new section on careers overview page
---------
- Corrected on Index page the wrong style for title
> [WIP] New Job: Senior Success Manager

- site/content/english/sav-fsa.md
- site/content/french/sav-fsa.md
- site/content/german/sav-fsa.md
text and pic changes about the offer for the members in:
DE
EN
FR
> [MRG] text change - SAV-FSA Mitglieder

- site/content/english/identification.md
- site/content/french/identification.md
- site/content/german/identification.md
The e-Ids that we've integrated or are about to integrate do not yet allow to sign with QES. That's why we add FES.
> [MRG] Add FES to e-ID picture 

- site/content/english/identification.md
The English acronym is AES and not FES
xref #430
> [MRG] Fix use of FES acronym in english content

- site/content/english/signaturestandards.md
The english version used EES instead of SES.
Closes https://app.asana.com/0/1117355270601225/1185668616070905
> [MRG] content(signaturestandards): fix SES acronym

- site/content/english/terms-of-use-archive.md
- site/content/english/terms-of-use-v2020-08-19.md
- site/content/french/terms-of-use-archive.md
- site/content/french/terms-of-use-v2020-08-19.md
- site/content/german/terms-of-use-archive.md
- site/content/german/terms-of-use-v2020-08-19.md
Closes parts of https://app.asana.com/0/1187035237749018/1186660118928177
> [MRG] update(ToU): implement new ToU

- site/content/german/careers/senior-success-manager.md
Changed on Senior Success Manager the wrong text
> [WIP] Senior Success Manager - text correction

- site/content/english/contact.md
- site/content/french/contact.md
- site/content/german/contact.md
We don't only have a Zurich office anymore
> [MRG] New lead on Contact Page

- site/content/english/signaturestandards.md
- site/content/french/signaturestandards.md
- site/content/german/signaturestandards.md
Added note on legal-weight table - page: signaturestandard
> [MRG] Signaturestandard - note for legal-weight barometer

- site/content/english/enable-qes.md
- site/content/french/enable-qes.md
- site/content/german/enable-qes.md
Implements: https://app.asana.com/0/1189216070187244/1189027931633893
> [MRG] feat(Ident Locations): Removes maps

- site/static/my.skribble/status.txt
> [MRG] Typo tweak

- site/static/my.skribble/status.txt
> Revert "content(status.txt): show "QES unavailable" banner on my.skribble.com"

- site/content/french/enable-qes.md
- site/content/german/enable-qes.md
Add a little sentence that informs the user they're about to leave for an english page, regardless of their language.
> feat: Page is only available in english

- site/content/english/enable-qes.md
- site/content/french/enable-qes.md
- site/content/german/enable-qes.md
Instead of linking to the Swisscom page. It's a revert of #470
> Reintroduce locations on our site

- site/content/german/_index.md
We use some Swiss German words that we would like to exchange with German words
> Replace "innert" with "innerhalb von"

- site/content/english/press-room.md
- site/content/french/press-room.md
- site/content/german/press-room.md
We grow fast, so the number changes all the time anyways
> Remove number of employees Press Room

- site/content/english/pricing.md
- site/content/french/pricing.md
- site/content/german/pricing.md
> Add Tick for Customer Success Team for ENT

- package.json
- yarn.lock
Couldn't be automatically updated by dependabot :(
> build(deps): Bump yargs-parser to 13.1.2

- site/content/english/pricing.md
> Remove Typos EN 

- site/content/english/expert-suisse.md
- site/content/french/expert-suisse.md
- site/content/german/expert-suisse.md
> [MRG] EXPERTsuisse LP content change

- site/content/english/enable-qes.md
- site/content/german/enable-qes.md
From "Identifikation im persönlichen Kontakt" to "persönliche Identifikation vor Ort"
> Change wording DE

- site/content/english/identification/aes-for-business/index.md
- site/content/french/identification/aes-for-business/index.md
- site/content/german/identifikation/aes-for-business/index.md
> Anpassungen AES4Biz 

- site/config.yaml
- site/content/english/integration.md
- site/content/french/integration.md
- site/content/german/integration.md
https://app.asana.com/0/1199139943296662/1199147146451277
> [MRG] Update links to API documentation to api-doc.skribble.com

- site/layouts/status/single.html
- Show maintenance info and icons during maintenance. 
- Cleared with Waldemar/Maxim: Show maintenance entries 10 days before maintenance.
https://app.asana.com/0/1198186801388194/1182290274395505
> Statuspage maintenance updates

- site/content/english/careers/account-executive.md
- site/content/english/careers/success-manager.md
- site/content/french/careers/account-executive.md
- site/content/french/careers/success-manager.md
- site/content/german/careers/account-executive.md
- site/content/german/careers/success-manager.md
> Exchange Links to Applied

- site/content/english/pricing.md
- site/content/french/pricing.md
- site/content/german/pricing.md
> Adapt pricing info
