site/layouts/_default/baseof.html, site/layouts/partials/header.html, site/layouts/partials/intro.html, site/layouts/partials/mobile-nav.html, src/css/imports/block.scss, src/css/imports/collapsible.scss, src/css/imports/compliance.scss, src/css/imports/header.scss, src/css/imports/intro.scss, src/css/imports/mixins.scss, src/css/imports/mobile-nav.scss, src/css/imports/price-plan.scss, src/css/imports/title-subtitle.scss, src/css/imports/vars.css, src/css/main.scss
Add arial and sans-serif as font-fallback that is shown before the Averta font has been loaded
(previously a serif font was shown). Fix issues with global padding on mobile.
=> feat(mobile nav): add mobile nav in css only version

src/css/imports/mobile-nav.scss
Initializing with the transition of translating the navigation out of the viewport had the effect
that the navigation quickly flashed on the screen of desktop viewports when loading.
=> [MRG] fix(mobile nav): set initial position to off-screen

site/content/english/_index.md, site/content/german/_index.md, site/layouts/partials/intro.html, src/css/imports/btn.scss
First call to action (_try Skribble now_) was missing on mobile. A button has been added to the intro component that sits at the very top of the homepage. The button is also visible on desktop viewports.
=> [MRG] feat(home): add try it now action for mobile on homepage

src/css/imports/footer.scss
Navigation is unreadable and not clickable because of the fixed height of the footer.
=> [MRG] fix(footer): fix issue where height of mobile footer was restricted

site/layouts/partials/footer.html, site/layouts/partials/language-switch-js.html, site/layouts/partials/mobile-nav.html
Only the switcher in the footer was functional because it was picked up via an ID by javascript. Changed the query selector to target via a class, prefixed with js to reduce the probability of a naming collision.
=> [MRG] fix(language switcher): make the language switcher work within the mobile nav 

site/layouts/partials/footer-language-switcher.html, site/layouts/partials/language-switch-js.html, src/css/main.scss
Some pages of the Skribble website were wider than narrow viewports. This caused horizontal
scrolling on mobile phones. Fixes JS error when newLocation is undefined because of missing french pages.
=> fix(mobile): set maximum width to 100 viewport units

site/static/my.skribble/status.txt
Reverts BlockSigner/cove#115
So we don't get surprised by a banner suddenly appearing because we forgot we had it activated.
=> [MRG] Revert "Update status.txt"

site/config.yaml
On /de at bottom left there was a wrong link.
Closes https://app.asana.com/0/1117355270601225/1129356036141381
=> [MRG] chore(site/config.yaml): set proper link

site/layouts/_default/baseof.html, src/css/main.scss
In order to get a better UX on slow mobile connections, we change the
Averta @font-face to use 'fallback' instead of the default which is most
likely 'block'. Additionally we set 'sans-serif' as a fallback font when
Averta loads too slow.
See also https://developers.google.com/web/updates/2016/02/font-display
Closes https://app.asana.com/0/995964219886332/1118204062378468
=> [MRG] styling(fonts): change font-display to 'fallback'

site/layouts/_default/baseof.html
By bundling the Matomo JavaScript tracker directly into the container it may improve the performance of your website as it reduces the number of needed requests.
=> Update (baseof): deleted Matomo js

README.md, site/layouts/shortcodes/plan.html
This PR also updates the readme.
See the outline button on the left side. You cannot see anything in the Netlify Preview as the button is not in use yet.
=> [MRG] feat(Plan): Add option to add outline buttons to plan

site/content/german/identification.md
A German word with English spelling.
=> [MRG] Fix typo

site/static/my.skribble/status.txt
Letting users know that they can't access their documents. Vault is unreachable atm.
=> [MRG] Vault unreachable status message

package.json, yarn.lock
Packages `webpack` and `webpack-dev-server` had a dependency on package `set-value` which reported several security flaws. This PR updates those packages.
Shouldn't cause any issues since it's not a major version upgrade, however webpack is quite low level and we don't have a powerful Dominik around to test 🙂 Some quick clicking around on a few browsers/devices would be cool
=> [MRG] build(Webpack): Updates webpack to solve security warnings

site/config.yaml, site/content/english/privacy.md, site/content/english/signaturestandards.md, site/content/french/privacy.md, site/content/german/privacy.md
Changed typo in year (20161) - OR article EN on the signature standard page
=> [MRG] Typo, link, order corrections

site/layouts/partials/footer-navigation.html
Because of Hugo restrictions on Menu fields definition it is not possible to have manually set target fields with our current code.
However, it's quite straightforward to make external links automatically have `target="_blank"`.
This should solve https://app.asana.com/0/995964219886332/1157719763255473/f
=> [MRG] feat(Footer links): Make external links open in new window

site/layouts/_default/baseof.html
Before, it was static: www.skribble.com
This PR changes the open graph url meta tag to point to the url of the page you're currently on. It should prevent shared urls in LinkedIn to be redirect to the Skribble home page.
=> [MRG] feat(Open graph): Add current permalink as og url

site/content/german/terms-of-use.md
- Added missing word "keine" before "Schadsoftware"
=> [MRG] Missing word "keine" in terms-of-use

README.md
Corrects the link in the readme to the h1 content (this always happens since github and VS Code parse markdown links differently and I forget to test the links in the PR).
Also, re-writes a bit of the content for improved readability.
=> [MRG] docs(Single H1 per page): Corrects link and improves content

site/content/english/enable-qes.md, site/content/french/enable-qes.md, site/content/german/enable-qes.md
Reverts BlockSigner/cove#410
Because "next week the previous person is back from vacation"
=> Revert "[MRG] feat(Update Flexoffice Details): Changes phone number and office name"

site/content/french/privacy-v2019-10-22.md, site/content/german/privacy-v2019-10-22.md, site/static/cookieconsent/config.js
Adds German and French content to the cookie consent user flow with content translated by our team.
The file `site/static/cookieconsent/config.js` has been prettified so shows more changes than the actual code changes.
=> [MRG] feat(Localised cookie banner): Re-introduces German and French content

site/static/cookieconsent/config.js, src/css/imports/cookie-consent.scss, src/css/main.scss
- ~~Klaro preferences moved to localStorage~~
- Klaro preferences moved to a cookie with domain `.skribble.com` so that they can be accessed by Wave (by default it would give the domain `www.skribble.com` to the cookie)
- Small notification only shows buttons "Accept All" and customize
- When you customize, cookies are disabled by default
- Removes "Powered by Klaro"
- Adds mention of Google Tag Manager (which Till will introduce via Hubspot)
- Improves styling
=> [MRG] feat(Cookie consent improvements): Functional and styling improvements

site/layouts/shortcodes/cookie-resetter.html
The built in function from klaro (our cookie consent library) to reset cookies doesn't seem play well with explicitly defined domains.
This PR replaces that function with a "brute force" deletion of all cookies currently accessible to the browser window.
Does not mess with the only cookie which is really relevant to safeguard in our cookie flow. This would be `x-access-token` from Wave. It won't touch that one, since it has domain `my.skribble.com` and not `.skribble.com`. So, it's not accesible.
Unfortunately it can only be fully tested once it reaches production.
=> [MRG] fix(Cookie consent reset): Fixes cookie consent resetting

site/static/my.skribble/status.txt
Swisscom had to roll back their DN placeholder implementation. Problems
persist.
=> status(SC): add "degraded service" banner

site/content/english/gtc-v2020-08-19.md, site/content/english/terms-of-use-v2020-08-19.md, site/content/french/gtc-v2020-08-19.md, site/content/french/terms-of-use-v2020-08-19.md, site/content/german/gtc-v2020-08-19.md, site/content/german/terms-of-use-v2020-08-19.md
They were introduced as a copy-paste leftover from older versions which
used to use that URL scheme. But not anymore.
Closes https://app.asana.com/0/1191332220899194/1189770700812225
=> chore(aliases): remove unnecessary aliases from GTC and ToU

site/content/english/privacy-archive.md, site/content/english/privacy-v2020-09-17.md, site/content/french/privacy-archive.md, site/content/french/privacy-v2020-09-17.md, site/content/german/privacy-archive.md, site/content/german/privacy-v2020-09-17.md
The privacy policy took a bit longer to be finalised and went online on
the Sep 17 2020.
=> chore(privacy policy): adapt date to actual publication date

site/content/german/enable-qes.md
The German version of the link seems to have vanished, we now
link to the English page.
=> [MRG] Fix SRS link

src/css/imports/intro.scss
This PR reduces list item margins inside of the intro component. The intro component is only used on the home page and 2 hidden pages. It has no effect as there are no lists used within intro. The PR prepares the styling for lists appearing in the PRs #463 and #475.
=> feat(intro): Reduce whitespace between list items

site/config.yaml
Apparently our helpcenter uses `/de` in the language-specific start
pages. For some reason `/francais` and `/english` are properly
redirected whereas `/deutsch` leads to a 404.
Closes https://app.asana.com/0/1117355270601225/1199388812156205
=> fix(site/config.yaml): fix broken german helpcenter link in footer

README.md
Adds a note to the README to let people know that this repo has been archived. If we merge this we should also click "archive" in the [settings](https://github.com/BlockSigner/cove/settings) (down in the danger zone) of this repo. Which should make it hard to open a PR or edit things without noticing.
=> Add archived notice to README
